name: aqua_mate
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.9.2

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8

  # â¬‡ Add these here (NOT inside flutter:)
  flutter_local_notifications: ^17.1.2
  timezone: ^0.9.2

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/images/logo.png
    - assets/images/library/freshwater.png
    - assets/images/library/saltwater.png
    - assets/images/library/aquascape.png
    - assets/images/library/fresh_fish/guppy-blue.webp
    - assets/images/library/fresh_fish/blue_angelfish.png
    - assets/images/library/fresh_fish/golden-fish-black.jpg
    - assets/images/library/fresh_fish/betta.jpg
    - assets/images/library/salt_fish/clown-fish.webp
    - assets/images/library/salt_fish/yellow_tang.jpeg
    - assets/images/library/salt_fish/mandarin_dragonet.jpg
    - assets/images/library/salt_fish/blue_tang.jpeg


